# Generated by Django 4.1.5 on 2023-02-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturebbs", "0002_pictures_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pictures",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
    ]
